### ISSUE TITLE
Another project for CSV-to-YNAB conversion

### ISSUE THREAD

**Issue by torbengb** [figueredo/bank2ynab#1]
Hello Tiago!
I've seen that you have a YNAB repository on GitHub. Have you seen that there are many similar projects? There is one in particular that could be very interesting for you: "bank2ynab"
https://github.com/torbengb/bank2ynab/blob/develop/README.md

If you could provide a sample CSV export (anonymized) then we could easily create the converter for your bank, too! 

We would also like to know the default filename for the exported CSV, so we can identify it and use the proper converter.

Let me know what you think!
Best regards from snowy Austria,
Ben

**Comment by figueredo** [comment]
Hi Ben!

I didn't know this project, great work you are doing here!

Unfortunately my project is very tied to my YNAB workflow, so I'm not sure if I can help you. Currently I copy the statement from the bank's website and paste it into a .txt file, then I use the converter from [figueredo/bank2ynab](https://github.com/figueredo/bank2ynab) to create a CSV that YNAB understands. Would it be of any help?

**Comment by torbengb** [comment]
Thanks for the response! I understand your workflow, and it's different from "bank2ynab". If you would still like to help us, I'd be interested in an actual CSV export file, rather than copying from the screen. We're interested in the column order, header row, and filename. This is of course assuming that your banking website offers a CSV export function!
Kind regards,
Ben

**Comment by torbengb** [comment]
Hello again! Just a friendly reminder, if you don't mind. It would be great to know the default file name of the CSV export, and a sample file.
Thank you,
-Ben

**Comment by figueredo** [comment]
Hi Ben, what makes me copy & paste from their website is the lack of an export function:
- Alelo doesn't have any way to export data;
- Itau exports in some formats (XLS, OFC and OFX) for the checkings account, which are already directly supported by YNAB. For their credit cards though there isn't a way to export data;
- Nubank exports to OFX, but only when the statement is closed, no way otherwise.
My idea is to implement this export to avoid the manual copy & paste, but I think I won't be able to do it in the short term...

**Comment by torbengb** [comment]
Thank you for the response!
I am frankly amazed, shocked, that a bank does not offer an export - in
2018! But I believe you; you seem to know it very well. I wish you the very
best with your efforts!

As for our "bank2ynab", I think we will close our ticket because there is
no reliable CSV option. Thank you again!
-Ben,

**Comment by figueredo** [comment]
I feel the same! It is quite sad actually, sad but true... Sorry for not being able to help and I wish you the best too!
